### ISSUE TITLE
请问 为什么npm install 以后访问8080 无法访问此网站？

### ISSUE THREAD

**Issue by 77266989** [linkingvision/h5svue#1]
代码 和 路由什么都没有改。安装 运行都没有报错。我其他的vue项目都可以正常运行。

**Comment by xsmart** [comment]
"dev": "webpack-dev-server --inline --progress --host 0.0.0.0 --port 6080 --config build/webpack.dev.conf.j
应该访问6080， 8080 是h5s 默认的端口，这里vue 默认的改了

**Comment by 77266989** [comment]
谢谢 看到啦！
