### ISSUE TITLE
vue 播放视频的url在哪里配置

### ISSUE THREAD

**Issue by 77266989** [linkingvision/h5svue#2]
没有发现html5的PDF说明里的那个文件源配置的文件。
 this.PlayVideo('token1'); 这个token1是不是就是对应的视频播放参数？token1对象的属性是什么样的（好像没有看到哪里可以配置的）？

**Comment by xsmart** [comment]
https://linkingvision.com/download/documentation/h5stream/h5stream%20%E4%B8%AD%E6%96%87%E4%BB%8B%E7%BB%8D%20r7.pdf 可以参考这个文档
